language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "q6K7e7wOmNv8HcML2e4/eZ3hJTFn2fZguDgEzQhAjsIx2R9F8S/W7NeiVxYY0xrjW4yw1+ouzvCgPRTvP6NRkrOMogOjRR8Cn8uXQ8R+YdQ5Dv02bNQIpp/8G/+AtFTxwL9g7MAVo9sOWP3mZGYuxhTPLW9D0wQcJARIxmOt+r6KjTRkvJkq9xm1kZG83xNNf7dDYCTHQR0/AnKAdYHu0sq3lnLqrx1lPWqtDQMfbQjbmZLEjtqgZLJcJK7DIjvTD00Itvq/j0ksishLoEiRfWo4IYM2CCMBQt0ahQd0GjxbLwX0c5hG1wOX7KYSH+Y5jTb4rrasDFsAdjgNOhsurepoogeGu0oX09VtUfsJIwBKlvESrJdLE3HyVg/d80vZahV2sdV2aaFkIw0BZWilRggWkxHqTI3D7Y1MwXlCYZ14pPuImQ+uoQswWWO2bltHz6ukahXwFuCOHTbJf3cYOhXiDjL5uINXufTTMHjg3xjb72O26yNyS2tSmpC7+3SHsUqW89Aw1vALsiF/mVvJ9+ewLN4/oOGznU/SIjt/ZYQlZrwF8cIhf7PPIXZldmYV16UtYyUpI0IrHZNBjeIAUmREtzEgVDU+/1dStYx/3fAlYqlcWD9v+Wtd4NxwpyfPrD7GddBJ4eoMXY4lmj5SThMpbVjnzuC8xcRY/sB6znE="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
